version: '3.8'

services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"  # Porta para conexões JMS/AMQP
      - "8161:8161"    # Console web do ActiveMQ
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
      - activemq-data:/var/lib/activemq/data
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    networks:
      - loki-network
    command: -config.file=/etc/loki/local-config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - C:\eclipe-workspace\climasync\logs:/var/log
    networks:
      - loki-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - loki-network
    depends_on:
      - loki

volumes:
  activemq-data:  # Volume para persistência dos dados do ActiveMQ
  loki-data:

networks:
  loki-network:
    driver: bridge